import mongoose from 'mongoose';
import * as fs from 'fs';
import * as path from 'path';

// Load .env.local manually
const envPath = path.join(process.cwd(), '.env.local');
if (fs.existsSync(envPath)) {
  const envContent = fs.readFileSync(envPath, 'utf-8');
  envContent.split('\n').forEach(line => {
    const [key, ...valueParts] = line.split('=');
    if (key && valueParts.length > 0) {
      process.env[key.trim()] = valueParts.join('=').trim();
    }
  });
}

const MONGODB_URI = process.env.MONGODB_URI || '';

// Store Product Schema (inline for script)
const StoreProductSchema = new mongoose.Schema({
  slug: { type: String, required: true, unique: true },
  name: { type: String, required: true },
  shortDescription: { type: String, required: true },
  fullDescription: { type: String, required: true },
  category: { type: String, required: true },
  subcategory: { type: String, required: true },
  brand: { type: String, required: true },
  sku: { type: String, required: true, unique: true },
  thumbnail: { type: String, required: true },
  images: [String],
  price: { type: Number, required: true },
  originalPrice: { type: Number, required: true },
  discount: { type: Number, default: 0 },
  currency: { type: String, default: 'BRL' },
  stock: { type: Number, default: 10 },
  isActive: { type: Boolean, default: true },
  isFeatured: { type: Boolean, default: false },
  isNewArrival: { type: Boolean, default: false },
  tags: [String],
  specifications: [{ key: String, value: String }],
  rating: { type: Number, default: 4.5 },
  reviewCount: { type: Number, default: 0 },
  soldCount: { type: Number, default: 0 },
  warranty: String,
  externalUrl: String,
}, { timestamps: true });

const StoreProduct = mongoose.models.StoreProduct || mongoose.model('StoreProduct', StoreProductSchema);

// Sample products data
const products = [
  // ==================== COMPUTERS ====================
  {
    slug: 'workstation-ia-pro-rtx4090',
    name: 'Workstation IA Pro RTX 4090',
    shortDescription: 'Estação de trabalho otimizada para Machine Learning e IA com RTX 4090',
    fullDescription: 'Workstation premium projetada para profissionais de IA e Machine Learning. Equipada com processador Intel Core i9-14900K, 128GB de RAM DDR5, e placa de vídeo NVIDIA RTX 4090 24GB.',
    category: 'computers',
    subcategory: 'Servidores IA',
    brand: 'FayaPoint Custom',
    sku: 'WS-IA-PRO-4090',
    thumbnail: 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=400',
    images: [],
    price: 45999.90,
    originalPrice: 52999.90,
    discount: 13,
    stock: 5,
    isFeatured: true,
    isNewArrival: true,
    tags: ['ia', 'machine learning', 'rtx 4090', 'workstation', 'profissional'],
    specifications: [
      { key: 'Processador', value: 'Intel Core i9-14900K' },
      { key: 'Memória RAM', value: '128GB DDR5 5600MHz' },
      { key: 'Placa de Vídeo', value: 'NVIDIA RTX 4090 24GB' },
      { key: 'Armazenamento', value: '2TB NVMe + 4TB SSD' },
      { key: 'Fonte', value: '1200W 80 Plus Platinum' },
    ],
    rating: 5.0,
    reviewCount: 28,
    soldCount: 47,
    warranty: '3 anos',
    externalUrl: 'https://www.nvidia.com/en-us/geforce/graphics-cards/40-series/rtx-4090/',
  },
  {
    slug: 'ilha-edicao-4k-creator',
    name: 'Ilha de Edição 4K Creator Edition',
    shortDescription: 'Computador otimizado para edição de vídeo 4K/8K com monitor incluso',
    fullDescription: 'Sistema completo para criadores de conteúdo. Inclui PC com AMD Ryzen 9 7950X, 64GB RAM, RTX 4080 e monitor ultrawide 34" calibrado de fábrica.',
    category: 'computers',
    subcategory: 'Ilhas de Edição',
    brand: 'FayaPoint Custom',
    sku: 'IE-4K-CREATOR',
    thumbnail: 'https://images.unsplash.com/photo-1593640408182-31c70c8268f5?w=400',
    images: [],
    price: 32499.90,
    originalPrice: 37999.90,
    discount: 15,
    stock: 8,
    isFeatured: true,
    tags: ['edição', 'vídeo', '4k', '8k', 'creator', 'davinci'],
    specifications: [
      { key: 'Processador', value: 'AMD Ryzen 9 7950X' },
      { key: 'Memória RAM', value: '64GB DDR5' },
      { key: 'Placa de Vídeo', value: 'NVIDIA RTX 4080 16GB' },
      { key: 'Monitor', value: '34" Ultrawide 144Hz' },
    ],
    rating: 4.9,
    reviewCount: 45,
    soldCount: 89,
    warranty: '3 anos',
  },
  {
    slug: 'pc-gamer-extreme-rtx4070',
    name: 'PC Gamer Extreme RTX 4070 Ti',
    shortDescription: 'Desktop gamer de alta performance para jogos em 4K',
    fullDescription: 'PC Gamer montado com os melhores componentes do mercado. Intel Core i7-14700K, 32GB RAM DDR5, RTX 4070 Ti 12GB, gabinete com RGB.',
    category: 'computers',
    subcategory: 'Desktops Completos',
    brand: 'FayaPoint Custom',
    sku: 'PC-GAMER-EXT-4070',
    thumbnail: 'https://images.unsplash.com/photo-1587831990711-23ca6441447b?w=400',
    images: [],
    price: 12999.90,
    originalPrice: 14999.90,
    discount: 13,
    stock: 15,
    isFeatured: true,
    isNewArrival: true,
    tags: ['gamer', 'gaming', 'rtx 4070', 'rgb', 'performance'],
    specifications: [
      { key: 'Processador', value: 'Intel Core i7-14700K' },
      { key: 'Memória RAM', value: '32GB DDR5' },
      { key: 'Placa de Vídeo', value: 'NVIDIA RTX 4070 Ti 12GB' },
      { key: 'SSD', value: '1TB NVMe' },
    ],
    rating: 4.8,
    reviewCount: 156,
    soldCount: 234,
    warranty: '2 anos',
  },
  {
    slug: 'mini-pc-intel-nuc-13',
    name: 'Mini PC Intel NUC 13 Pro',
    shortDescription: 'Mini PC compacto e potente para escritório e home office',
    fullDescription: 'Intel NUC 13 Pro com processador i7-1360P, 16GB RAM, 512GB SSD. Ideal para escritório, HTPC ou estação de trabalho compacta.',
    category: 'computers',
    subcategory: 'Mini PCs',
    brand: 'Intel',
    sku: 'NUC13-PRO-I7',
    thumbnail: 'https://images.unsplash.com/photo-1624823183493-ed5832f48f18?w=400',
    images: [],
    price: 4299.90,
    originalPrice: 4999.90,
    discount: 14,
    stock: 20,
    tags: ['mini pc', 'nuc', 'compacto', 'escritório'],
    specifications: [
      { key: 'Processador', value: 'Intel Core i7-1360P' },
      { key: 'Memória RAM', value: '16GB DDR4' },
      { key: 'SSD', value: '512GB NVMe' },
    ],
    rating: 4.6,
    reviewCount: 78,
    soldCount: 112,
    warranty: '2 anos',
  },

  // ==================== COMPONENTS ====================
  {
    slug: 'rtx-4090-founders-edition',
    name: 'NVIDIA GeForce RTX 4090 Founders Edition',
    shortDescription: 'A placa de vídeo mais poderosa para gamers e criadores',
    fullDescription: 'NVIDIA GeForce RTX 4090 com 24GB GDDR6X. O ápice do desempenho gráfico para jogos 4K, ray tracing e tarefas de IA.',
    category: 'components',
    subcategory: 'Placas de Vídeo',
    brand: 'NVIDIA',
    sku: 'RTX4090-FE',
    thumbnail: 'https://images.unsplash.com/photo-1591488320449-011701bb6704?w=400',
    images: [],
    price: 14999.90,
    originalPrice: 16999.90,
    discount: 12,
    stock: 7,
    isFeatured: true,
    tags: ['gpu', 'rtx 4090', 'nvidia', 'gaming', 'ia'],
    specifications: [
      { key: 'Memória', value: '24GB GDDR6X' },
      { key: 'CUDA Cores', value: '16384' },
      { key: 'Boost Clock', value: '2.52 GHz' },
      { key: 'TDP', value: '450W' },
    ],
    rating: 5.0,
    reviewCount: 89,
    soldCount: 145,
    warranty: '3 anos',
    externalUrl: 'https://www.nvidia.com/en-us/geforce/graphics-cards/40-series/rtx-4090/',
  },
  {
    slug: 'amd-ryzen-9-7950x3d',
    name: 'AMD Ryzen 9 7950X3D',
    shortDescription: 'O processador mais rápido para gaming com 3D V-Cache',
    fullDescription: 'AMD Ryzen 9 7950X3D com tecnologia 3D V-Cache. 16 núcleos, 32 threads, ideal para gaming e produtividade extrema.',
    category: 'components',
    subcategory: 'Processadores',
    brand: 'AMD',
    sku: 'AMD-7950X3D',
    thumbnail: 'https://images.unsplash.com/photo-1555617981-dac3880eac6e?w=400',
    images: [],
    price: 4299.90,
    originalPrice: 4999.90,
    discount: 14,
    stock: 12,
    isNewArrival: true,
    tags: ['cpu', 'amd', 'ryzen', 'gaming', '3d v-cache'],
    specifications: [
      { key: 'Núcleos', value: '16' },
      { key: 'Threads', value: '32' },
      { key: 'Cache Total', value: '144MB' },
      { key: 'TDP', value: '120W' },
    ],
    rating: 4.9,
    reviewCount: 234,
    soldCount: 378,
    warranty: '3 anos',
    externalUrl: 'https://www.amd.com/en/products/cpu/amd-ryzen-9-7950x3d',
  },
  {
    slug: 'corsair-vengeance-ddr5-64gb',
    name: 'Corsair Vengeance DDR5 64GB (2x32GB) 6000MHz',
    shortDescription: 'Kit de memória RAM DDR5 de alta performance',
    fullDescription: 'Kit Corsair Vengeance DDR5 64GB (2x32GB) 6000MHz CL36. Ideal para workstations e sistemas de alto desempenho.',
    category: 'components',
    subcategory: 'Memória RAM',
    brand: 'Corsair',
    sku: 'CMK64GX5M2B6000',
    thumbnail: 'https://images.unsplash.com/photo-1562976540-1502c2145186?w=400',
    images: [],
    price: 1899.90,
    originalPrice: 2299.90,
    discount: 17,
    stock: 25,
    tags: ['ram', 'ddr5', 'corsair', 'memoria'],
    specifications: [
      { key: 'Capacidade', value: '64GB (2x32GB)' },
      { key: 'Velocidade', value: '6000MHz' },
      { key: 'Latência', value: 'CL36' },
    ],
    rating: 4.7,
    reviewCount: 156,
    soldCount: 289,
    warranty: 'Lifetime',
    externalUrl: 'https://www.corsair.com/us/en/p/memory/cmk64gx5m2b6000z36/vengeancea-64gb-2x32gb-ddr5-dram-6000mt-s-cl36-intel-xmpa-3-0-memory-kit-a-black-cmk64gx5m2b6000z36',
  },
  {
    slug: 'samsung-990-pro-2tb',
    name: 'Samsung 990 Pro 2TB NVMe M.2',
    shortDescription: 'SSD NVMe PCIe 4.0 com velocidades extremas',
    fullDescription: 'Samsung 990 Pro 2TB NVMe M.2 com velocidades de leitura de até 7450MB/s. O SSD mais rápido para gaming e produtividade.',
    category: 'components',
    subcategory: 'SSDs e HDDs',
    brand: 'Samsung',
    sku: 'MZ-V9P2T0BW',
    thumbnail: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=400',
    images: [],
    price: 1299.90,
    originalPrice: 1599.90,
    discount: 19,
    stock: 30,
    isFeatured: true,
    tags: ['ssd', 'nvme', 'samsung', 'armazenamento'],
    specifications: [
      { key: 'Capacidade', value: '2TB' },
      { key: 'Leitura', value: '7450 MB/s' },
      { key: 'Gravação', value: '6900 MB/s' },
      { key: 'Interface', value: 'PCIe 4.0 x4' },
    ],
    rating: 4.9,
    reviewCount: 312,
    soldCount: 567,
    warranty: '5 anos',
  },

  // ==================== PERIPHERALS ====================
  {
    slug: 'logitech-g-pro-x-superlight-2',
    name: 'Logitech G Pro X Superlight 2',
    shortDescription: 'O mouse wireless mais leve e preciso para e-sports',
    fullDescription: 'Logitech G Pro X Superlight 2 com sensor HERO 2, 63g de peso, 95 horas de bateria. O preferido dos pro players.',
    category: 'peripherals',
    subcategory: 'Mouses',
    brand: 'Logitech',
    sku: 'GPRO-SL2-BLK',
    thumbnail: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400',
    images: [],
    price: 899.90,
    originalPrice: 999.90,
    discount: 10,
    stock: 35,
    isFeatured: true,
    isNewArrival: true,
    tags: ['mouse', 'wireless', 'logitech', 'esports', 'gaming'],
    specifications: [
      { key: 'Sensor', value: 'HERO 2' },
      { key: 'DPI', value: 'até 32.000' },
      { key: 'Peso', value: '63g' },
      { key: 'Bateria', value: '95 horas' },
    ],
    rating: 4.9,
    reviewCount: 456,
    soldCount: 789,
    warranty: '2 anos',
  },
  {
    slug: 'razer-deathadder-v3-pro',
    name: 'Razer DeathAdder V3 Pro',
    shortDescription: 'Mouse ergonômico wireless de alta performance',
    fullDescription: 'Razer DeathAdder V3 Pro com sensor Focus Pro 30K, 63g, switches ópticos de 3a geração. Design ergonômico icônico.',
    category: 'peripherals',
    subcategory: 'Mouses',
    brand: 'Razer',
    sku: 'RZ01-04630100',
    thumbnail: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=400',
    images: [],
    price: 799.90,
    originalPrice: 899.90,
    discount: 11,
    stock: 28,
    tags: ['mouse', 'razer', 'ergonômico', 'wireless'],
    specifications: [
      { key: 'Sensor', value: 'Focus Pro 30K' },
      { key: 'DPI', value: 'até 30.000' },
      { key: 'Peso', value: '63g' },
    ],
    rating: 4.8,
    reviewCount: 345,
    soldCount: 567,
    warranty: '2 anos',
  },
  {
    slug: 'artisan-hayate-otsu-xl',
    name: 'Artisan Hayate Otsu XL',
    shortDescription: 'Mousepad japonês premium para gaming competitivo',
    fullDescription: 'Mousepad Artisan Hayate Otsu XL. Fabricação artesanal japonesa, superfície de controle balanceado, base de espuma Urethan.',
    category: 'peripherals',
    subcategory: 'Mousepads',
    brand: 'Artisan',
    sku: 'ARTISAN-HAYATE-XL',
    thumbnail: 'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=400',
    images: [],
    price: 349.90,
    originalPrice: 399.90,
    discount: 13,
    stock: 15,
    isNewArrival: true,
    tags: ['mousepad', 'artisan', 'gaming', 'esports'],
    specifications: [
      { key: 'Dimensões', value: '490 x 420 x 4mm' },
      { key: 'Superfície', value: 'Tecido híbrido' },
      { key: 'Base', value: 'Urethan foam' },
    ],
    rating: 4.9,
    reviewCount: 234,
    soldCount: 456,
    warranty: '1 ano',
  },
  {
    slug: 'logitech-g915-tkl',
    name: 'Logitech G915 TKL Lightspeed',
    shortDescription: 'Teclado mecânico wireless low-profile premium',
    fullDescription: 'Logitech G915 TKL com switches GL Tactile, RGB LIGHTSYNC, Lightspeed wireless e Bluetooth. Design slim profissional.',
    category: 'peripherals',
    subcategory: 'Teclados',
    brand: 'Logitech',
    sku: 'G915-TKL-TACT',
    thumbnail: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400',
    images: [],
    price: 1499.90,
    originalPrice: 1799.90,
    discount: 17,
    stock: 18,
    isFeatured: true,
    tags: ['teclado', 'mecânico', 'wireless', 'logitech', 'rgb'],
    specifications: [
      { key: 'Switch', value: 'GL Tactile' },
      { key: 'Layout', value: 'TKL' },
      { key: 'Conectividade', value: 'Lightspeed + Bluetooth' },
    ],
    rating: 4.7,
    reviewCount: 289,
    soldCount: 445,
    warranty: '2 anos',
  },
  {
    slug: 'hyperx-cloud-iii-wireless',
    name: 'HyperX Cloud III Wireless',
    shortDescription: 'Headset wireless de alta fidelidade para gaming',
    fullDescription: 'HyperX Cloud III Wireless com drivers de 53mm, DTS Headphone:X, bateria de 120 horas, microfone destacável.',
    category: 'peripherals',
    subcategory: 'Headsets',
    brand: 'HyperX',
    sku: 'HYPERX-C3-WIRELESS',
    thumbnail: 'https://images.unsplash.com/photo-1599669454699-248893623440?w=400',
    images: [],
    price: 899.90,
    originalPrice: 999.90,
    discount: 10,
    stock: 22,
    tags: ['headset', 'wireless', 'hyperx', 'gaming'],
    specifications: [
      { key: 'Driver', value: '53mm' },
      { key: 'Bateria', value: '120 horas' },
      { key: 'Áudio', value: 'DTS Headphone:X' },
    ],
    rating: 4.6,
    reviewCount: 178,
    soldCount: 312,
    warranty: '2 anos',
  },
  {
    slug: 'elgato-wave-3',
    name: 'Elgato Wave:3 Premium USB Microphone',
    shortDescription: 'Microfone USB premium para streaming e podcasts',
    fullDescription: 'Elgato Wave:3 com cápsula condenser, resolução de 24-bit/96kHz, controle de ganho digital, software Wave Link.',
    category: 'peripherals',
    subcategory: 'Microfones',
    brand: 'Elgato',
    sku: 'ELGATO-WAVE3',
    thumbnail: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=400',
    images: [],
    price: 999.90,
    originalPrice: 1199.90,
    discount: 17,
    stock: 16,
    isNewArrival: true,
    tags: ['microfone', 'streaming', 'podcast', 'elgato'],
    specifications: [
      { key: 'Tipo', value: 'Condenser' },
      { key: 'Resolução', value: '24-bit/96kHz' },
      { key: 'Padrão Polar', value: 'Cardioide' },
    ],
    rating: 4.8,
    reviewCount: 234,
    soldCount: 389,
    warranty: '2 anos',
  },

  // ==================== MONITORS ====================
  {
    slug: 'lg-ultragear-27gp950',
    name: 'LG UltraGear 27GP950-B 4K 144Hz',
    shortDescription: 'Monitor gaming 4K com HDMI 2.1 para PS5 e PC',
    fullDescription: 'LG UltraGear 27" 4K UHD Nano IPS, 144Hz, 1ms, HDMI 2.1, G-Sync e FreeSync Premium Pro. Perfeito para gaming e produtividade.',
    category: 'monitors',
    subcategory: 'Monitores Gaming',
    brand: 'LG',
    sku: '27GP950-B',
    thumbnail: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400',
    images: [],
    price: 4499.90,
    originalPrice: 5299.90,
    discount: 15,
    stock: 12,
    isFeatured: true,
    tags: ['monitor', '4k', 'gaming', 'lg', 'hdmi 2.1'],
    specifications: [
      { key: 'Resolução', value: '3840 x 2160 (4K)' },
      { key: 'Taxa de Atualização', value: '144Hz' },
      { key: 'Painel', value: 'Nano IPS' },
      { key: 'Tempo de Resposta', value: '1ms' },
    ],
    rating: 4.8,
    reviewCount: 189,
    soldCount: 278,
    warranty: '3 anos',
  },
  {
    slug: 'samsung-odyssey-g9',
    name: 'Samsung Odyssey G9 49" DQHD 240Hz',
    shortDescription: 'Monitor ultrawide curvo 49" para imersão total',
    fullDescription: 'Samsung Odyssey G9 49" DQHD (5120x1440), 240Hz, 1ms, curvatura 1000R, HDR1000. A experiência de gaming mais imersiva.',
    category: 'monitors',
    subcategory: 'Ultrawide',
    brand: 'Samsung',
    sku: 'LC49G95TSSNXZA',
    thumbnail: 'https://images.unsplash.com/photo-1616763355548-1b606f439f86?w=400',
    images: [],
    price: 8999.90,
    originalPrice: 10999.90,
    discount: 18,
    stock: 6,
    isFeatured: true,
    isNewArrival: true,
    tags: ['monitor', 'ultrawide', 'curvo', 'samsung', '240hz'],
    specifications: [
      { key: 'Resolução', value: '5120 x 1440' },
      { key: 'Taxa de Atualização', value: '240Hz' },
      { key: 'Curvatura', value: '1000R' },
      { key: 'HDR', value: 'HDR1000' },
    ],
    rating: 4.7,
    reviewCount: 145,
    soldCount: 189,
    warranty: '3 anos',
  },
  {
    slug: 'benq-pd3220u',
    name: 'BenQ PD3220U 4K Designer Monitor',
    shortDescription: 'Monitor profissional 4K para design e edição',
    fullDescription: 'BenQ PD3220U 32" 4K UHD, 95% DCI-P3, Thunderbolt 3, calibrado de fábrica. Monitor profissional para designers e editores.',
    category: 'monitors',
    subcategory: 'Monitores Profissionais',
    brand: 'BenQ',
    sku: 'PD3220U',
    thumbnail: 'https://images.unsplash.com/photo-1585792180666-f7347c490ee2?w=400',
    images: [],
    price: 5999.90,
    originalPrice: 6999.90,
    discount: 14,
    stock: 9,
    tags: ['monitor', '4k', 'design', 'profissional', 'thunderbolt'],
    specifications: [
      { key: 'Resolução', value: '3840 x 2160 (4K)' },
      { key: 'Cor', value: '95% DCI-P3' },
      { key: 'Conectividade', value: 'Thunderbolt 3' },
    ],
    rating: 4.9,
    reviewCount: 98,
    soldCount: 156,
    warranty: '3 anos',
  },

  // ==================== ACCESSORIES ====================
  {
    slug: 'secretlab-titan-evo-2022',
    name: 'Secretlab TITAN Evo 2022',
    shortDescription: 'Cadeira ergonômica premium para longas sessões',
    fullDescription: 'Secretlab TITAN Evo 2022 Series com espuma fria de 4 camadas, lombar magnético, apoio de braço 4D. A cadeira definitiva.',
    category: 'accessories',
    subcategory: 'Cadeiras Gamer',
    brand: 'Secretlab',
    sku: 'TITAN-EVO-2022',
    thumbnail: 'https://images.unsplash.com/photo-1598550476439-6847785fcea6?w=400',
    images: [],
    price: 3499.90,
    originalPrice: 3999.90,
    discount: 13,
    stock: 14,
    isFeatured: true,
    tags: ['cadeira', 'ergonômica', 'secretlab', 'gaming'],
    specifications: [
      { key: 'Material', value: 'SoftWeave Plus' },
      { key: 'Suporte Lombar', value: 'Magnético ajustável' },
      { key: 'Peso Suportado', value: 'até 130kg' },
    ],
    rating: 4.9,
    reviewCount: 567,
    soldCount: 892,
    warranty: '5 anos',
  },
  {
    slug: 'elgato-stream-deck-xl',
    name: 'Elgato Stream Deck XL',
    shortDescription: 'Controlador LCD com 32 teclas para streaming',
    fullDescription: 'Elgato Stream Deck XL com 32 teclas LCD customizáveis. Controle total sobre OBS, Twitch, Discord e mais.',
    category: 'accessories',
    subcategory: 'Iluminação LED',
    brand: 'Elgato',
    sku: 'STREAMDECK-XL',
    thumbnail: 'https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?w=400',
    images: [],
    price: 1699.90,
    originalPrice: 1999.90,
    discount: 15,
    stock: 11,
    isNewArrival: true,
    tags: ['stream deck', 'streaming', 'elgato', 'controle'],
    specifications: [
      { key: 'Teclas', value: '32 LCD' },
      { key: 'Conexão', value: 'USB 3.0' },
    ],
    rating: 4.8,
    reviewCount: 345,
    soldCount: 567,
    warranty: '2 anos',
  },
  {
    slug: 'caldigit-ts4-dock',
    name: 'CalDigit TS4 Thunderbolt 4 Dock',
    shortDescription: 'Dock station premium com 18 portas',
    fullDescription: 'CalDigit TS4 com 18 portas incluindo 3x Thunderbolt 4, 98W power delivery, USB 4.0. O dock mais completo do mercado.',
    category: 'accessories',
    subcategory: 'Hubs USB',
    brand: 'CalDigit',
    sku: 'CALDIGIT-TS4',
    thumbnail: 'https://images.unsplash.com/photo-1625842268584-8f3296236761?w=400',
    images: [],
    price: 2499.90,
    originalPrice: 2899.90,
    discount: 14,
    stock: 8,
    tags: ['dock', 'thunderbolt', 'usb', 'hub'],
    specifications: [
      { key: 'Portas', value: '18 total' },
      { key: 'Power Delivery', value: '98W' },
      { key: 'Interface', value: 'Thunderbolt 4' },
    ],
    rating: 4.9,
    reviewCount: 189,
    soldCount: 278,
    warranty: '2 anos',
  },
  {
    slug: 'ergotron-lx-dual',
    name: 'Ergotron LX Dual Side-by-Side Arm',
    shortDescription: 'Suporte de monitor duplo premium',
    fullDescription: 'Ergotron LX Dual Side-by-Side Arm. Suporta dois monitores de até 27", movimento fluido, design premium.',
    category: 'accessories',
    subcategory: 'Suportes',
    brand: 'Ergotron',
    sku: 'ERGOTRON-LX-DUAL',
    thumbnail: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=400',
    images: [],
    price: 1899.90,
    originalPrice: 2199.90,
    discount: 14,
    stock: 13,
    tags: ['suporte', 'monitor', 'ergotron', 'dual'],
    specifications: [
      { key: 'Monitores', value: '2x até 27"' },
      { key: 'Peso Suportado', value: 'até 9.1kg cada' },
    ],
    rating: 4.8,
    reviewCount: 234,
    soldCount: 389,
    warranty: '10 anos',
  },

  // ==================== SOFTWARE ====================
  {
    slug: 'microsoft-365-family',
    name: 'Microsoft 365 Family - 1 Ano',
    shortDescription: 'Assinatura completa do Office para até 6 pessoas',
    fullDescription: 'Microsoft 365 Family com Word, Excel, PowerPoint, Outlook, 1TB OneDrive por pessoa, para até 6 usuários por 1 ano.',
    category: 'software',
    subcategory: 'Suítes Office',
    brand: 'Microsoft',
    sku: 'M365-FAMILY-1Y',
    thumbnail: 'https://images.unsplash.com/photo-1633419461186-7d40a38105ec?w=400',
    images: [],
    price: 449.90,
    originalPrice: 549.90,
    discount: 18,
    stock: 999,
    tags: ['microsoft', 'office', '365', 'produtividade'],
    specifications: [
      { key: 'Usuários', value: 'Até 6' },
      { key: 'Armazenamento', value: '1TB por pessoa' },
      { key: 'Duração', value: '12 meses' },
    ],
    rating: 4.7,
    reviewCount: 678,
    soldCount: 1234,
    warranty: 'N/A',
  },
  {
    slug: 'davinci-resolve-studio',
    name: 'DaVinci Resolve Studio',
    shortDescription: 'Software profissional de edição de vídeo e color grading',
    fullDescription: 'DaVinci Resolve Studio - Licença perpétua. Edição, color grading, VFX e pós-produção de áudio em um só software.',
    category: 'software',
    subcategory: 'Editores de Vídeo',
    brand: 'Blackmagic Design',
    sku: 'DAVINCI-STUDIO',
    thumbnail: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=400',
    images: [],
    price: 1999.90,
    originalPrice: 2299.90,
    discount: 13,
    stock: 999,
    isFeatured: true,
    tags: ['davinci', 'edição', 'vídeo', 'color grading'],
    specifications: [
      { key: 'Licença', value: 'Perpétua' },
      { key: 'Atualizações', value: 'Gratuitas' },
    ],
    rating: 4.9,
    reviewCount: 456,
    soldCount: 789,
    warranty: 'N/A',
  },

  // ==================== NETWORKING ====================
  {
    slug: 'asus-rog-rapture-gt-ax11000',
    name: 'ASUS ROG Rapture GT-AX11000 Pro',
    shortDescription: 'Roteador tri-band WiFi 6E para gaming',
    fullDescription: 'ASUS ROG Rapture GT-AX11000 Pro WiFi 6E tri-band com velocidades de até 11000Mbps, Game Mode, VPN Fusion.',
    category: 'networking',
    subcategory: 'Roteadores',
    brand: 'ASUS',
    sku: 'ROG-GT-AX11000-PRO',
    thumbnail: 'https://images.unsplash.com/photo-1606904825846-647eb07f5be2?w=400',
    images: [],
    price: 2999.90,
    originalPrice: 3499.90,
    discount: 14,
    stock: 10,
    isNewArrival: true,
    tags: ['roteador', 'wifi 6e', 'gaming', 'asus rog'],
    specifications: [
      { key: 'WiFi', value: '6E Tri-band' },
      { key: 'Velocidade', value: 'até 11000 Mbps' },
      { key: 'Portas', value: '2x 10G + 4x Gigabit' },
    ],
    rating: 4.7,
    reviewCount: 156,
    soldCount: 234,
    warranty: '3 anos',
  },

  // ==================== STORAGE ====================
  {
    slug: 'synology-ds923',
    name: 'Synology DS923+ NAS 4-Bay',
    shortDescription: 'NAS profissional para backup e mídia',
    fullDescription: 'Synology DS923+ NAS 4-bay com AMD Ryzen, suporte a cache SSD M.2, 10GbE opcional. Ideal para home office e pequenas empresas.',
    category: 'storage',
    subcategory: 'NAS',
    brand: 'Synology',
    sku: 'DS923+',
    thumbnail: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400',
    images: [],
    price: 4299.90,
    originalPrice: 4999.90,
    discount: 14,
    stock: 7,
    tags: ['nas', 'synology', 'backup', 'storage'],
    specifications: [
      { key: 'Baias', value: '4' },
      { key: 'CPU', value: 'AMD Ryzen R1600' },
      { key: 'RAM', value: '4GB (exp. 32GB)' },
    ],
    rating: 4.8,
    reviewCount: 189,
    soldCount: 278,
    warranty: '3 anos',
  },
  {
    slug: 'sandisk-extreme-pro-portable-4tb',
    name: 'SanDisk Extreme Pro Portable SSD 4TB',
    shortDescription: 'SSD externo ultra-rápido e resistente',
    fullDescription: 'SanDisk Extreme Pro Portable 4TB com velocidades de até 2000MB/s, IP65 resistente a água e poeira.',
    category: 'storage',
    subcategory: 'HDs Externos',
    brand: 'SanDisk',
    sku: 'SDSSDE81-4T00',
    thumbnail: 'https://images.unsplash.com/photo-1531492746076-161ca9bcad58?w=400',
    images: [],
    price: 2999.90,
    originalPrice: 3499.90,
    discount: 14,
    stock: 16,
    tags: ['ssd', 'externo', 'portátil', 'sandisk'],
    specifications: [
      { key: 'Capacidade', value: '4TB' },
      { key: 'Velocidade', value: 'até 2000 MB/s' },
      { key: 'Resistência', value: 'IP65' },
    ],
    rating: 4.8,
    reviewCount: 234,
    soldCount: 389,
    warranty: '5 anos',
  },

  // ==================== PRINT ON DEMAND ====================
  {
    slug: 'camiseta-dev-ai-prompt-engineer',
    name: 'Camiseta Dev "Prompt Engineer" Premium',
    shortDescription: 'Camiseta 100% algodão para desenvolvedores e entusiastas de IA',
    fullDescription: 'Camiseta premium com estampa exclusiva "Prompt Engineer". Perfeita para quem trabalha com inteligência artificial. 100% algodão pré-encolhido, impressão DTG de alta qualidade.',
    category: 'pod',
    subcategory: 'Camisetas',
    brand: 'FayaPoint POD',
    sku: 'POD-TSHIRT-PROMPT-ENG',
    thumbnail: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400',
    images: [],
    price: 89.90,
    originalPrice: 109.90,
    discount: 18,
    stock: 999,
    isFeatured: true,
    isNewArrival: true,
    tags: ['camiseta', 'dev', 'programador', 'ia', 'prompt engineer', 'pod'],
    specifications: [
      { key: 'Material', value: '100% Algodão' },
      { key: 'Impressão', value: 'DTG Alta Qualidade' },
      { key: 'Tamanhos', value: 'P, M, G, GG, XG' },
      { key: 'Fornecedor', value: 'Printify' },
    ],
    rating: 4.8,
    reviewCount: 156,
    soldCount: 423,
    warranty: '30 dias',
  },
  {
    slug: 'moletom-code-coffee-repeat',
    name: 'Moletom "Code. Coffee. Repeat." Unisex',
    shortDescription: 'Moletom confortável para programadores viciados em café',
    fullDescription: 'Moletom unisex com capuz e bolso canguru. Estampa "Code. Coffee. Repeat." Tecido macio e quentinho, perfeito para longas sessões de código.',
    category: 'pod',
    subcategory: 'Moletons',
    brand: 'FayaPoint POD',
    sku: 'POD-HOODIE-CODE-COFFEE',
    thumbnail: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=400',
    images: [],
    price: 189.90,
    originalPrice: 229.90,
    discount: 17,
    stock: 999,
    isFeatured: true,
    tags: ['moletom', 'hoodie', 'dev', 'programador', 'café', 'pod'],
    specifications: [
      { key: 'Material', value: '80% Algodão, 20% Poliéster' },
      { key: 'Peso', value: '280g/m²' },
      { key: 'Tamanhos', value: 'P, M, G, GG, XG' },
      { key: 'Fornecedor', value: 'Printful' },
    ],
    rating: 4.9,
    reviewCount: 89,
    soldCount: 267,
    warranty: '30 dias',
  },
  {
    slug: 'caneca-ai-overlord',
    name: 'Caneca "I, for one, welcome our AI Overlords"',
    shortDescription: 'Caneca de cerâmica 325ml com humor tech',
    fullDescription: 'Caneca de cerâmica de alta qualidade com estampa de humor sobre inteligência artificial. Perfeita para o café da manhã no escritório ou home office.',
    category: 'pod',
    subcategory: 'Canecas',
    brand: 'FayaPoint POD',
    sku: 'POD-MUG-AI-OVERLORD',
    thumbnail: 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=400',
    images: [],
    price: 49.90,
    originalPrice: 59.90,
    discount: 17,
    stock: 999,
    tags: ['caneca', 'mug', 'ia', 'humor', 'escritório', 'pod'],
    specifications: [
      { key: 'Material', value: 'Cerâmica' },
      { key: 'Capacidade', value: '325ml' },
      { key: 'Impressão', value: 'Sublimação' },
      { key: 'Fornecedor', value: 'Printify' },
    ],
    rating: 4.7,
    reviewCount: 234,
    soldCount: 567,
    warranty: '30 dias',
  },
  {
    slug: 'poster-neural-network-art',
    name: 'Poster "Neural Network" Arte Minimalista',
    shortDescription: 'Poster artístico de rede neural em alta resolução',
    fullDescription: 'Poster minimalista representando uma rede neural. Impressão em papel premium 250g/m² com cores vibrantes. Perfeito para decorar o escritório de qualquer entusiasta de IA.',
    category: 'pod',
    subcategory: 'Posters',
    brand: 'FayaPoint POD',
    sku: 'POD-POSTER-NEURAL-NET',
    thumbnail: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=400',
    images: [],
    price: 79.90,
    originalPrice: 99.90,
    discount: 20,
    stock: 999,
    isNewArrival: true,
    tags: ['poster', 'arte', 'neural network', 'ia', 'decoração', 'pod'],
    specifications: [
      { key: 'Tamanhos', value: 'A4, A3, A2, A1' },
      { key: 'Papel', value: '250g/m² Premium' },
      { key: 'Acabamento', value: 'Semi-Fosco' },
      { key: 'Fornecedor', value: 'Prodigi' },
    ],
    rating: 4.8,
    reviewCount: 145,
    soldCount: 389,
    warranty: '30 dias',
  },
  {
    slug: 'quadro-canvas-circuit-board',
    name: 'Quadro Canvas "Circuit Board" Premium',
    shortDescription: 'Quadro em canvas com arte de circuito eletrônico',
    fullDescription: 'Quadro em canvas de alta qualidade com arte inspirada em placas de circuito. Estrutura em madeira, pronto para pendurar. Perfeito para decoração tech.',
    category: 'pod',
    subcategory: 'Canvas',
    brand: 'FayaPoint POD',
    sku: 'POD-CANVAS-CIRCUIT',
    thumbnail: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=400',
    images: [],
    price: 199.90,
    originalPrice: 249.90,
    discount: 20,
    stock: 999,
    isFeatured: true,
    tags: ['canvas', 'quadro', 'circuito', 'tech', 'decoração', 'pod'],
    specifications: [
      { key: 'Tamanhos', value: '30x40cm, 50x70cm, 60x90cm' },
      { key: 'Material', value: 'Canvas Premium 400g/m²' },
      { key: 'Moldura', value: 'Madeira Pinus' },
      { key: 'Fornecedor', value: 'Prodigi' },
    ],
    rating: 4.9,
    reviewCount: 78,
    soldCount: 189,
    warranty: '1 ano',
  },
  {
    slug: 'capinha-iphone-binary-code',
    name: 'Capinha iPhone "Binary Code" Premium',
    shortDescription: 'Capinha de proteção com estampa de código binário',
    fullDescription: 'Capinha premium para iPhone com design de código binário. Material resistente a impactos, protege contra quedas. Disponível para todos os modelos de iPhone.',
    category: 'pod',
    subcategory: 'Capinhas',
    brand: 'FayaPoint POD',
    sku: 'POD-CASE-BINARY',
    thumbnail: 'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=400',
    images: [],
    price: 69.90,
    originalPrice: 89.90,
    discount: 22,
    stock: 999,
    tags: ['capinha', 'case', 'iphone', 'binário', 'tech', 'pod'],
    specifications: [
      { key: 'Modelos', value: 'iPhone 12-16 (todas variantes)' },
      { key: 'Material', value: 'TPU + Policarbonato' },
      { key: 'Proteção', value: 'Queda de até 2m' },
      { key: 'Fornecedor', value: 'Printify' },
    ],
    rating: 4.6,
    reviewCount: 312,
    soldCount: 678,
    warranty: '6 meses',
  },
  {
    slug: 'almofada-hello-world',
    name: 'Almofada "Hello World" Developer',
    shortDescription: 'Almofada decorativa para programadores',
    fullDescription: 'Almofada macia com estampa "Hello World" em diferentes linguagens de programação. Perfeita para decorar o escritório ou quarto. Enchimento de fibra siliconada.',
    category: 'pod',
    subcategory: 'Almofadas',
    brand: 'FayaPoint POD',
    sku: 'POD-PILLOW-HELLO-WORLD',
    thumbnail: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=400',
    images: [],
    price: 89.90,
    originalPrice: 109.90,
    discount: 18,
    stock: 999,
    tags: ['almofada', 'pillow', 'dev', 'hello world', 'decoração', 'pod'],
    specifications: [
      { key: 'Tamanhos', value: '40x40cm, 50x50cm' },
      { key: 'Capa', value: 'Poliéster Premium' },
      { key: 'Enchimento', value: 'Fibra Siliconada' },
      { key: 'Fornecedor', value: 'Gooten' },
    ],
    rating: 4.7,
    reviewCount: 167,
    soldCount: 345,
    warranty: '30 dias',
  },
  {
    slug: 'ecobag-think-different',
    name: 'Ecobag "Think Different, Code Better"',
    shortDescription: 'Sacola ecológica reutilizável para devs',
    fullDescription: 'Ecobag em algodão cru com alças reforçadas. Design minimalista "Think Different, Code Better". Ideal para compras, academia ou carregar o notebook.',
    category: 'pod',
    subcategory: 'Bolsas',
    brand: 'FayaPoint POD',
    sku: 'POD-TOTE-THINK-DIFF',
    thumbnail: 'https://images.unsplash.com/photo-1597484661643-2f5fef640dd1?w=400',
    images: [],
    price: 59.90,
    originalPrice: 69.90,
    discount: 14,
    stock: 999,
    tags: ['ecobag', 'tote', 'sacola', 'dev', 'sustentável', 'pod'],
    specifications: [
      { key: 'Material', value: 'Algodão Cru 280g/m²' },
      { key: 'Dimensões', value: '40x35cm' },
      { key: 'Alças', value: 'Reforçadas 60cm' },
      { key: 'Fornecedor', value: 'Printful' },
    ],
    rating: 4.8,
    reviewCount: 234,
    soldCount: 567,
    warranty: '30 dias',
  },
];

async function seedProducts() {
  try {
    console.log('Connecting to MongoDB...');
    await mongoose.connect(MONGODB_URI, { dbName: 'fayapoint' });
    console.log('Connected!');

    // Clear existing products
    console.log('Clearing existing products...');
    await StoreProduct.deleteMany({});

    // Insert new products
    console.log('Inserting products...');
    const result = await StoreProduct.insertMany(products);
    console.log(`Inserted ${result.length} products successfully!`);

    // Show summary by category
    const summary = await StoreProduct.aggregate([
      { $group: { _id: '$category', count: { $sum: 1 } } }
    ]);
    console.log('\nProducts by category:');
    summary.forEach(cat => {
      console.log(`  ${cat._id}: ${cat.count}`);
    });

    await mongoose.disconnect();
    console.log('\nDone!');
  } catch (error) {
    console.error('Error seeding products:', error);
    process.exit(1);
  }
}

seedProducts();
