import { MongoClient } from "mongodb";
import type { ServicePriceDocument } from "../src/lib/pricing";

const DEFAULT_MONGODB_URI = '';

const DATABASE_NAME = "fayapointProdutos";
const COLLECTION_NAME = "products_prices";

const LAST_VALIDATED_AT = new Date("2025-11-01T00:00:00Z").toISOString();

const servicePrices: ServicePriceDocument[] = [
  {
    category: "web",
    serviceSlug: "website-full",
    track: "Discovery",
    unitLabel: "Brand & Goals Workshop",
    description: "Two 2-hour stakeholder sessions to align on positioning, audience, and objectives.",
    unitType: "per_project",
    minQuantity: 1,
    defaultQuantity: 1,
    priceRange: { currency: "USD", min: 600, recommended: 900, max: 1200 },
    tags: ["strategy", "workshop"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "web",
    serviceSlug: "website-full",
    track: "Discovery",
    unitLabel: "Technical Architecture Blueprint",
    description: "System diagram, hosting approach, and stack recommendations for the full build.",
    unitType: "per_project",
    minQuantity: 1,
    defaultQuantity: 1,
    priceRange: { currency: "USD", min: 750, recommended: 1200, max: 1800 },
    tags: ["architecture"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "web",
    serviceSlug: "website-full",
    track: "UX",
    unitLabel: "Sitemap & User Flows",
    description: "Journey diagrams and acceptance criteria for up to five core flows.",
    unitType: "per_project",
    minQuantity: 1,
    defaultQuantity: 1,
    priceRange: { currency: "USD", min: 400, recommended: 650, max: 900 },
    tags: ["ux"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "web",
    serviceSlug: "website-full",
    track: "UX",
    unitLabel: "Wireframes",
    description: "Low/medium fidelity layouts per screen with annotations.",
    unitType: "per_screen",
    minQuantity: 1,
    defaultQuantity: 5,
    priceRange: { currency: "USD", min: 150, recommended: 220, max: 320 },
    tags: ["wireframe"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "web",
    serviceSlug: "website-full",
    track: "UI",
    unitLabel: "Visual Design",
    description: "High-fidelity responsive UI design per screen.",
    unitType: "per_screen",
    minQuantity: 1,
    defaultQuantity: 5,
    priceRange: { currency: "USD", min: 250, recommended: 380, max: 520 },
    tags: ["ui"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "web",
    serviceSlug: "website-full",
    track: "UI",
    unitLabel: "Design System Kit",
    description: "Token library, component catalog, and usage documentation.",
    unitType: "per_project",
    minQuantity: 1,
    defaultQuantity: 1,
    priceRange: { currency: "USD", min: 1200, recommended: 1800, max: 2500 },
    tags: ["design-system"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "web",
    serviceSlug: "website-full",
    track: "Content",
    unitLabel: "Copywriting",
    description: "SEO-optimized messaging per 500-word block.",
    unitType: "per_page",
    minQuantity: 1,
    defaultQuantity: 4,
    priceRange: { currency: "USD", min: 180, recommended: 260, max: 360 },
    tags: ["content"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "web",
    serviceSlug: "website-full",
    track: "Content",
    unitLabel: "Illustration Pack",
    description: "Custom vector or lightweight 3D set (4 assets).",
    unitType: "per_project",
    minQuantity: 1,
    defaultQuantity: 1,
    priceRange: { currency: "USD", min: 400, recommended: 600, max: 900 },
    tags: ["illustration"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "web",
    serviceSlug: "website-full",
    track: "Development",
    unitLabel: "Front-end Build",
    description: "Next.js responsive implementation per designed screen.",
    unitType: "per_screen",
    minQuantity: 1,
    defaultQuantity: 5,
    priceRange: { currency: "USD", min: 350, recommended: 520, max: 750 },
    tags: ["frontend"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "web",
    serviceSlug: "website-full",
    track: "Development",
    unitLabel: "CMS Integration",
    description: "CMS schema design and hooks per collection.",
    unitType: "per_collection",
    minQuantity: 1,
    defaultQuantity: 2,
    priceRange: { currency: "USD", min: 300, recommended: 460, max: 680 },
    tags: ["cms"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "web",
    serviceSlug: "website-full",
    track: "Development",
    unitLabel: "Backend/API Module",
    description: "Secured CRUD or integration endpoint with unit tests.",
    unitType: "per_project",
    minQuantity: 1,
    defaultQuantity: 1,
    priceRange: { currency: "USD", min: 600, recommended: 900, max: 1400 },
    tags: ["backend"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "web",
    serviceSlug: "website-full",
    track: "QA",
    unitLabel: "Functional QA Sweep",
    description: "Regression + bugfix cycle per release.",
    unitType: "per_release",
    minQuantity: 1,
    defaultQuantity: 1,
    priceRange: { currency: "USD", min: 450, recommended: 650, max: 900 },
    tags: ["qa"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "web",
    serviceSlug: "website-full",
    track: "QA",
    unitLabel: "Accessibility Compliance",
    description: "WCAG 2.1 AA audit with remediation notes.",
    unitType: "per_project",
    minQuantity: 1,
    defaultQuantity: 1,
    priceRange: { currency: "USD", min: 650, recommended: 950, max: 1400 },
    tags: ["a11y"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "web",
    serviceSlug: "website-full",
    track: "Launch",
    unitLabel: "DevOps & Hosting Setup",
    description: "Vercel/Cloudflare deployment, monitoring, and SSL.",
    unitType: "per_project",
    minQuantity: 1,
    defaultQuantity: 1,
    priceRange: { currency: "USD", min: 500, recommended: 800, max: 1200 },
    tags: ["devops"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "web",
    serviceSlug: "website-full",
    track: "Launch",
    unitLabel: "Training & Handoff",
    description: "Two-hour enablement session plus documentation.",
    unitType: "per_project",
    minQuantity: 1,
    defaultQuantity: 1,
    priceRange: { currency: "USD", min: 300, recommended: 450, max: 600 },
    tags: ["training"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "web",
    serviceSlug: "website-full",
    track: "Care",
    unitLabel: "Maintenance Retainer",
    description: "8 hours of prioritized support, updates, and monitoring per month.",
    unitType: "per_month",
    minQuantity: 1,
    defaultQuantity: 3,
    priceRange: { currency: "USD", min: 650, recommended: 950, max: 1500 },
    tags: ["retainer"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "social",
    serviceSlug: "social-management",
    track: "Strategy",
    unitLabel: "Audit & Roadmap",
    description: "Channel deep dive, KPI alignment, and 90-day roadmap per brand.",
    unitType: "per_project",
    minQuantity: 1,
    defaultQuantity: 1,
    priceRange: { currency: "USD", min: 700, recommended: 1050, max: 1600 },
    tags: ["strategy"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "social",
    serviceSlug: "social-management",
    track: "Strategy",
    unitLabel: "Content Pillar Sprint",
    description: "Defines three pillars, tone board, and campaign hooks.",
    unitType: "per_project",
    minQuantity: 1,
    defaultQuantity: 1,
    priceRange: { currency: "USD", min: 500, recommended: 750, max: 1100 },
    tags: ["content"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "social",
    serviceSlug: "social-management",
    track: "Production",
    unitLabel: "Static Post Design",
    description: "Carousel or single image with editable source files.",
    unitType: "per_project",
    minQuantity: 4,
    defaultQuantity: 12,
    priceRange: { currency: "USD", min: 90, recommended: 140, max: 220 },
    tags: ["design"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "social",
    serviceSlug: "social-management",
    track: "Production",
    unitLabel: "Short-form Video",
    description: "≤60s vertical edit with captions and motion graphics.",
    unitType: "per_project",
    minQuantity: 2,
    defaultQuantity: 4,
    priceRange: { currency: "USD", min: 220, recommended: 360, max: 520 },
    tags: ["video"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "social",
    serviceSlug: "social-management",
    track: "Production",
    unitLabel: "Copy Pack",
    description: "Five platform-ready captions with CTA and hashtags.",
    unitType: "per_project",
    minQuantity: 1,
    defaultQuantity: 2,
    priceRange: { currency: "USD", min: 120, recommended: 180, max: 260 },
    tags: ["copy"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "social",
    serviceSlug: "social-management",
    track: "Scheduling",
    unitLabel: "Publishing & Tagging",
    description: "Scheduling, UTM tracking, and QA per channel per month.",
    unitType: "per_month",
    minQuantity: 1,
    defaultQuantity: 2,
    priceRange: { currency: "USD", min: 180, recommended: 260, max: 420 },
    tags: ["operations"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "social",
    serviceSlug: "social-management",
    track: "Community",
    unitLabel: "Inbox & Moderation",
    description: "Live responses, escalations, and tagging per hour.",
    unitType: "per_hour",
    minQuantity: 5,
    defaultQuantity: 10,
    priceRange: { currency: "USD", min: 45, recommended: 65, max: 110 },
    tags: ["community"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "social",
    serviceSlug: "social-management",
    track: "Community",
    unitLabel: "Crisis Escalation Playbook",
    description: "Decision tree, templates, and war-room plan.",
    unitType: "per_project",
    minQuantity: 1,
    defaultQuantity: 1,
    priceRange: { currency: "USD", min: 350, recommended: 520, max: 780 },
    tags: ["crisis"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "social",
    serviceSlug: "social-management",
    track: "Analytics",
    unitLabel: "Monthly Performance Report",
    description: "Cross-channel KPIs, insights, and optimization backlog.",
    unitType: "per_month",
    minQuantity: 1,
    defaultQuantity: 3,
    priceRange: { currency: "USD", min: 260, recommended: 380, max: 540 },
    tags: ["reporting"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "social",
    serviceSlug: "social-management",
    track: "Paid",
    unitLabel: "Campaign Build",
    description: "Creative, targeting, pixel, and QA per ad set.",
    unitType: "per_project",
    minQuantity: 1,
    defaultQuantity: 2,
    priceRange: { currency: "USD", min: 280, recommended: 420, max: 650 },
    tags: ["ads"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "social",
    serviceSlug: "social-management",
    track: "Paid",
    unitLabel: "Optimization Retainer",
    description: "Weekly tuning and budget shifts per platform.",
    unitType: "per_month",
    minQuantity: 1,
    defaultQuantity: 3,
    priceRange: { currency: "USD", min: 450, recommended: 700, max: 1050 },
    tags: ["ads"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "local-seo",
    serviceSlug: "local-seo",
    track: "Setup",
    unitLabel: "Google Business Profile Creation",
    description: "Verification, branding, and services setup for one location.",
    unitType: "per_project",
    minQuantity: 1,
    defaultQuantity: 1,
    priceRange: { currency: "USD", min: 150, recommended: 260, max: 420 },
    tags: ["gbp"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "local-seo",
    serviceSlug: "local-seo",
    track: "Setup",
    unitLabel: "NAP Consistency Sweep",
    description: "Directory cleanup and citation accuracy per location.",
    unitType: "per_project",
    minQuantity: 1,
    defaultQuantity: 1,
    priceRange: { currency: "USD", min: 200, recommended: 320, max: 520 },
    tags: ["citations"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "local-seo",
    serviceSlug: "local-seo",
    track: "Optimization",
    unitLabel: "Listing Enhancement Sprint",
    description: "Photos, products, FAQs, and offer updates.",
    unitType: "per_project",
    minQuantity: 1,
    defaultQuantity: 1,
    priceRange: { currency: "USD", min: 180, recommended: 280, max: 450 },
    tags: ["optimization"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "local-seo",
    serviceSlug: "local-seo",
    track: "Optimization",
    unitLabel: "Localized Landing Page",
    description: "City-specific page with schema markup and CTA.",
    unitType: "per_page",
    minQuantity: 1,
    defaultQuantity: 2,
    priceRange: { currency: "USD", min: 380, recommended: 560, max: 820 },
    tags: ["content"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "local-seo",
    serviceSlug: "local-seo",
    track: "Reputation",
    unitLabel: "Review Response Management",
    description: "Personalized replies for each block of 20 reviews.",
    unitType: "per_project",
    minQuantity: 1,
    defaultQuantity: 2,
    priceRange: { currency: "USD", min: 140, recommended: 210, max: 320 },
    tags: ["reputation"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "local-seo",
    serviceSlug: "local-seo",
    track: "Reputation",
    unitLabel: "Review Generation Workflow",
    description: "Email/SMS automation to request and route reviews.",
    unitType: "per_project",
    minQuantity: 1,
    defaultQuantity: 1,
    priceRange: { currency: "USD", min: 350, recommended: 520, max: 780 },
    tags: ["automation"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "local-seo",
    serviceSlug: "local-seo",
    track: "Citations",
    unitLabel: "Directory Submission",
    description: "Submission to 10 industry-relevant directories.",
    unitType: "per_project",
    minQuantity: 1,
    defaultQuantity: 1,
    priceRange: { currency: "USD", min: 170, recommended: 240, max: 360 },
    tags: ["citations"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "local-seo",
    serviceSlug: "local-seo",
    track: "Reporting",
    unitLabel: "Local Pack Dashboard",
    description: "Monthly ranking, call, and direction insights.",
    unitType: "per_month",
    minQuantity: 1,
    defaultQuantity: 3,
    priceRange: { currency: "USD", min: 220, recommended: 330, max: 490 },
    tags: ["reporting"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "video",
    serviceSlug: "video-production",
    track: "Pre-Production",
    unitLabel: "Concept Treatment",
    description: "Narrative outline, moodboard, and creative direction.",
    unitType: "per_project",
    minQuantity: 1,
    defaultQuantity: 1,
    priceRange: { currency: "USD", min: 450, recommended: 680, max: 950 },
    tags: ["concept"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "video",
    serviceSlug: "video-production",
    track: "Pre-Production",
    unitLabel: "Scriptwriting",
    description: "Narrative script and VO cues per finished minute.",
    unitType: "per_minute",
    minQuantity: 1,
    defaultQuantity: 3,
    priceRange: { currency: "USD", min: 180, recommended: 260, max: 360 },
    tags: ["script"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "video",
    serviceSlug: "video-production",
    track: "Pre-Production",
    unitLabel: "Storyboard",
    description: "Frame-by-frame visualization per finished minute.",
    unitType: "per_minute",
    minQuantity: 1,
    defaultQuantity: 3,
    priceRange: { currency: "USD", min: 220, recommended: 320, max: 460 },
    tags: ["storyboard"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "video",
    serviceSlug: "video-production",
    track: "Pre-Production",
    unitLabel: "Casting & Talent Management",
    description: "Sourcing, auditions, and contracting per talent.",
    unitType: "per_project",
    minQuantity: 1,
    defaultQuantity: 1,
    priceRange: { currency: "USD", min: 280, recommended: 420, max: 620 },
    tags: ["talent"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "video",
    serviceSlug: "video-production",
    track: "Production",
    unitLabel: "Director Day Rate",
    description: "On-set creative leadership per day.",
    unitType: "per_day",
    minQuantity: 1,
    defaultQuantity: 1,
    priceRange: { currency: "USD", min: 850, recommended: 1200, max: 1800 },
    tags: ["production"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "video",
    serviceSlug: "video-production",
    track: "Production",
    unitLabel: "DP & Camera Package",
    description: "Director of Photography plus cinema kit per day.",
    unitType: "per_day",
    minQuantity: 1,
    defaultQuantity: 1,
    priceRange: { currency: "USD", min: 950, recommended: 1450, max: 2200 },
    tags: ["production"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "video",
    serviceSlug: "video-production",
    track: "Production",
    unitLabel: "Gaffer & Lighting Kit",
    description: "Lighting design, crew, and fixtures per day.",
    unitType: "per_day",
    minQuantity: 1,
    defaultQuantity: 1,
    priceRange: { currency: "USD", min: 600, recommended: 900, max: 1300 },
    tags: ["lighting"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "video",
    serviceSlug: "video-production",
    track: "Production",
    unitLabel: "Audio Engineer",
    description: "On-set sound mixing and boom operation per day.",
    unitType: "per_day",
    minQuantity: 1,
    defaultQuantity: 1,
    priceRange: { currency: "USD", min: 450, recommended: 680, max: 950 },
    tags: ["audio"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "video",
    serviceSlug: "video-production",
    track: "Production",
    unitLabel: "Drone Add-on",
    description: "Licensed drone pilot and footage per flight hour.",
    unitType: "per_hour",
    minQuantity: 1,
    defaultQuantity: 2,
    priceRange: { currency: "USD", min: 320, recommended: 480, max: 680 },
    tags: ["drone"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "video",
    serviceSlug: "video-production",
    track: "Post-Production",
    unitLabel: "Editing",
    description: "Assembly, pacing, and refinements per finished minute.",
    unitType: "per_minute",
    minQuantity: 1,
    defaultQuantity: 3,
    priceRange: { currency: "USD", min: 300, recommended: 450, max: 650 },
    tags: ["editing"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "video",
    serviceSlug: "video-production",
    track: "Post-Production",
    unitLabel: "Motion Graphics",
    description: "2D/3D graphics and animated titles per finished minute.",
    unitType: "per_minute",
    minQuantity: 1,
    defaultQuantity: 2,
    priceRange: { currency: "USD", min: 280, recommended: 420, max: 680 },
    tags: ["motion"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "video",
    serviceSlug: "video-production",
    track: "Post-Production",
    unitLabel: "Color Correction",
    description: "Balance and match grade per finished minute.",
    unitType: "per_minute",
    minQuantity: 1,
    defaultQuantity: 3,
    priceRange: { currency: "USD", min: 150, recommended: 230, max: 360 },
    tags: ["color"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "video",
    serviceSlug: "video-production",
    track: "Post-Production",
    unitLabel: "Color Grading Premium",
    description: "Look development and HDR mastering per day.",
    unitType: "per_day",
    minQuantity: 1,
    defaultQuantity: 1,
    priceRange: { currency: "USD", min: 650, recommended: 950, max: 1400 },
    tags: ["color"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "video",
    serviceSlug: "video-production",
    track: "Post-Production",
    unitLabel: "Sound Design & Mix",
    description: "FX, VO cleanup, and mastering per finished minute.",
    unitType: "per_minute",
    minQuantity: 1,
    defaultQuantity: 3,
    priceRange: { currency: "USD", min: 180, recommended: 260, max: 380 },
    tags: ["audio"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "video",
    serviceSlug: "video-production",
    track: "Post-Production",
    unitLabel: "Subtitles & Localization",
    description: "Burned or sidecar captions per language.",
    unitType: "per_language",
    minQuantity: 1,
    defaultQuantity: 2,
    priceRange: { currency: "USD", min: 120, recommended: 180, max: 260 },
    tags: ["localization"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "video",
    serviceSlug: "video-production",
    track: "Delivery",
    unitLabel: "Mastering & Exports",
    description: "QC and export package per format.",
    unitType: "per_format",
    minQuantity: 1,
    defaultQuantity: 2,
    priceRange: { currency: "USD", min: 90, recommended: 140, max: 210 },
    tags: ["delivery"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "video",
    serviceSlug: "video-production",
    track: "Delivery",
    unitLabel: "Usage Rights Extension",
    description: "Licensing beyond default term per year.",
    unitType: "per_project",
    minQuantity: 1,
    defaultQuantity: 1,
    priceRange: { currency: "USD", min: 220, recommended: 320, max: 480 },
    tags: ["licensing"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "automation",
    serviceSlug: "automation-ai",
    track: "Strategy",
    unitLabel: "Process Mapping Workshop",
    description: "Full-day audit to identify automation and AI opportunities.",
    unitType: "per_project",
    minQuantity: 1,
    defaultQuantity: 1,
    priceRange: { currency: "USD", min: 900, recommended: 1350, max: 1900 },
    tags: ["workshop"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "automation",
    serviceSlug: "automation-ai",
    track: "Strategy",
    unitLabel: "Automation Roadmap Deck",
    description: "Prioritized backlog with ROI modeling and sequencing.",
    unitType: "per_project",
    minQuantity: 1,
    defaultQuantity: 1,
    priceRange: { currency: "USD", min: 700, recommended: 1050, max: 1500 },
    tags: ["strategy"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "automation",
    serviceSlug: "automation-ai",
    track: "Build",
    unitLabel: "Workflow Implementation",
    description: "Trigger, logic, QA, and documentation per workflow.",
    unitType: "per_workflow",
    minQuantity: 1,
    defaultQuantity: 3,
    priceRange: { currency: "USD", min: 450, recommended: 700, max: 1050 },
    tags: ["workflow"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "automation",
    serviceSlug: "automation-ai",
    track: "Build",
    unitLabel: "API/CRM Integration",
    description: "Authentication, sync logic, and monitoring per system.",
    unitType: "per_project",
    minQuantity: 1,
    defaultQuantity: 2,
    priceRange: { currency: "USD", min: 600, recommended: 900, max: 1400 },
    tags: ["integration"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "automation",
    serviceSlug: "automation-ai",
    track: "Build",
    unitLabel: "AI Agent Prompt Pack",
    description: "Multi-step instruction set with guardrails per agent.",
    unitType: "per_project",
    minQuantity: 1,
    defaultQuantity: 2,
    priceRange: { currency: "USD", min: 320, recommended: 480, max: 720 },
    tags: ["ai"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "automation",
    serviceSlug: "automation-ai",
    track: "Build",
    unitLabel: "Knowledge Base Ingestion",
    description: "Chunking, embeddings, and evals per 1k docs.",
    unitType: "per_project",
    minQuantity: 1,
    defaultQuantity: 1,
    priceRange: { currency: "USD", min: 500, recommended: 750, max: 1100 },
    tags: ["ai"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "automation",
    serviceSlug: "automation-ai",
    track: "QA",
    unitLabel: "Automation Testing Suite",
    description: "Unit, regression, and rollback plan per workflow.",
    unitType: "per_workflow",
    minQuantity: 1,
    defaultQuantity: 3,
    priceRange: { currency: "USD", min: 220, recommended: 330, max: 520 },
    tags: ["qa"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "automation",
    serviceSlug: "automation-ai",
    track: "Enablement",
    unitLabel: "Team Training Session",
    description: "Two-hour enablement session with office hours.",
    unitType: "per_project",
    minQuantity: 1,
    defaultQuantity: 1,
    priceRange: { currency: "USD", min: 280, recommended: 420, max: 620 },
    tags: ["training"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "automation",
    serviceSlug: "automation-ai",
    track: "Support",
    unitLabel: "Monitoring & Optimization",
    description: "Alerting, tweaks, and reporting per month.",
    unitType: "per_month",
    minQuantity: 1,
    defaultQuantity: 3,
    priceRange: { currency: "USD", min: 550, recommended: 820, max: 1250 },
    tags: ["support"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "packages",
    serviceSlug: "bundles",
    track: "Package",
    unitLabel: "Local Authority Launch",
    description: "GBP setup, listing enhancement, 2 localized pages, and review workflow.",
    unitType: "per_project",
    minQuantity: 1,
    defaultQuantity: 1,
    priceRange: { currency: "USD", min: 2450, recommended: 2450, max: 3000 },
    tags: ["bundle"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "packages",
    serviceSlug: "bundles",
    track: "Package",
    unitLabel: "Content Engine Pro",
    description: "Strategy audit, 12 static posts, 4 reels, moderation 10h, and reporting.",
    unitType: "per_project",
    minQuantity: 1,
    defaultQuantity: 1,
    priceRange: { currency: "USD", min: 4250, recommended: 4250, max: 5200 },
    tags: ["bundle"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "packages",
    serviceSlug: "bundles",
    track: "Package",
    unitLabel: "Conversion Website Sprint",
    description: "Discovery, 8 UX/UI screens, copy, FE build, CMS, QA, and launch.",
    unitType: "per_project",
    minQuantity: 1,
    defaultQuantity: 1,
    priceRange: { currency: "USD", min: 11800, recommended: 11800, max: 13500 },
    tags: ["bundle"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "packages",
    serviceSlug: "bundles",
    track: "Package",
    unitLabel: "Video Growth Kit",
    description: "Concept, script, storyboard, 2 production days, edit, color, sound, subtitles.",
    unitType: "per_project",
    minQuantity: 1,
    defaultQuantity: 1,
    priceRange: { currency: "USD", min: 14600, recommended: 14600, max: 16500 },
    tags: ["bundle"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
  {
    category: "packages",
    serviceSlug: "bundles",
    track: "Package",
    unitLabel: "AI Automation Jumpstart",
    description: "Workshop, roadmap, 3 workflows, CRM integration, training, 2 months support.",
    unitType: "per_project",
    minQuantity: 1,
    defaultQuantity: 1,
    priceRange: { currency: "USD", min: 9800, recommended: 9800, max: 11500 },
    tags: ["bundle"],
    lastValidatedAt: LAST_VALIDATED_AT,
  },
];

async function seed() {
  const uri = process.env.MONGODB_URI ?? DEFAULT_MONGODB_URI;
  const client = new MongoClient(uri);

  try {
    console.log("🔌 Connecting to MongoDB...");
    await client.connect();
    console.log("✅ Connected");

    const collection = client
      .db(DATABASE_NAME)
      .collection<ServicePriceDocument>(COLLECTION_NAME);

    await collection.createIndex(
      { serviceSlug: 1, unitLabel: 1 },
      { unique: true, name: "idx_service_unit" },
    );

    let inserted = 0;
    let updated = 0;

    for (const doc of servicePrices) {
      const now = new Date().toISOString();
      const payload = {
        ...doc,
        lastValidatedAt: doc.lastValidatedAt ?? LAST_VALIDATED_AT,
        updatedAt: now,
      } as ServicePriceDocument;

      const result = await collection.updateOne(
        { serviceSlug: doc.serviceSlug, unitLabel: doc.unitLabel },
        {
          $set: payload,
          $setOnInsert: { createdAt: now },
        },
        { upsert: true },
      );

      if (result.upsertedCount && result.upsertedCount > 0) {
        inserted += 1;
        console.log(`  ➕ Inserted ${doc.serviceSlug} - ${doc.unitLabel}`);
      } else if (result.modifiedCount > 0) {
        updated += 1;
        console.log(`  🔄 Updated ${doc.serviceSlug} - ${doc.unitLabel}`);
      }
    }

    console.log("\n🎯 Seeding complete");
    console.log(`   Inserted: ${inserted}`);
    console.log(`   Updated: ${updated}`);
    console.log(`   Total processed: ${servicePrices.length}`);
  } catch (error) {
    console.error("❌ Error seeding service prices", error);
    process.exitCode = 1;
  } finally {
    await client.close();
    console.log("👋 Connection closed");
  }
}

seed();
